// ─────────────────────────────────────────────
// user.js — User profile and email routes
// ─────────────────────────────────────────────

const express          = require('express');
const router           = express.Router();
const { db, auth: adminAuth, admin } = require('../services/firebase');
const { authenticate } = require('../middleware/authenticate');
const { sendVerificationEmail, sendPasswordResetEmail } = require('../services/emailService');

// ─────────────────────────────────────────────
// HELPER — replaces Firebase's default handler
// domain with our custom action.html page.
//
// Firebase generates links pointing to:
// https://[project].firebaseapp.com/__/auth/action
//
// We replace that with:
// https://mycybershieldai.web.app/action.html
//
// The oobCode and mode parameters remain valid
// because they are generated by Firebase —
// only the delivery URL changes.
// ─────────────────────────────────────────────

function useCustomHandler(firebaseLink) {
  return firebaseLink.replace(
    /https:\/\/[a-z0-9-]+\.firebaseapp\.com\/__\/auth\/action/,
    `${process.env.FRONTEND_URL}/action.html`
  );
}

// ─────────────────────────────────────────────
// POST /api/user/profile
// ─────────────────────────────────────────────

router.post('/profile', authenticate, async (req, res) => {
  const { firstName, lastName, username, country, displayName } = req.body;
  const uid   = req.user.uid;
  const email = req.user.email;

  try {
    if (username) {
      const taken = await db.collection('users')
        .where('username', '==', username.toLowerCase())
        .get();

      if (taken.docs.some(d => d.id !== uid)) {
        return res.status(409).json({
          success: false,
          error  : 'Username already taken. Please choose another.'
        });
      }
    }

    await db.collection('users').doc(uid).set({
      uid,
      email,
      firstName  : firstName   || '',
      lastName   : lastName    || '',
      username   : username    ? username.toLowerCase() : '',
      displayName: displayName || `${firstName} ${lastName}`,
      country    : country     || '',
      createdAt  : new Date().toISOString(),
      scanCount  : 0
    }, { merge: true });

    res.status(200).json({ success: true });

  } catch (error) {
    console.error('[PROFILE ERROR]', error.message);
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// GET /api/user/profile
// ─────────────────────────────────────────────

router.get('/profile', authenticate, async (req, res) => {
  try {
    const doc = await db.collection('users').doc(req.user.uid).get();

    if (!doc.exists) {
      return res.status(404).json({ success: false, error: 'Profile not found.' });
    }

    res.status(200).json({ success: true, profile: doc.data() });

  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// PUT /api/user/profile
// ─────────────────────────────────────────────

router.put('/profile', authenticate, async (req, res) => {
  const { firstName, lastName, country } = req.body;

  try {
    await db.collection('users').doc(req.user.uid).update({
      firstName,
      lastName,
      country,
      displayName: `${firstName} ${lastName}`,
      updatedAt  : new Date().toISOString()
    });

    res.status(200).json({ success: true });

  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// GET /api/user/scans
// ─────────────────────────────────────────────

// GET /api/user/scans
router.get('/scans', authenticate, async (req, res) => {
  try {
    // No orderBy — avoids requiring a Firestore composite index
    // Sorting is done client-side in the dashboard
    const snapshot = await db.collection('scans')
      .where('uid', '==', req.user.uid)
      .limit(100)
      .get();

    const scans = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
    res.status(200).json({ success: true, scans });

  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// DELETE /api/user/scans/:scanId
// ─────────────────────────────────────────────

router.delete('/scans/:scanId', authenticate, async (req, res) => {
  const uid = req.user.uid;
  const ref = db.collection('scans').doc(req.params.scanId);

  try {
    const doc = await ref.get();

    if (!doc.exists || doc.data().uid !== uid) {
      return res.status(403).json({ success: false, error: 'Forbidden.' });
    }

    await ref.delete();
    res.status(200).json({ success: true });

  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// POST /api/user/send-verification
// ─────────────────────────────────────────────

router.post('/send-verification', async (req, res) => {
  const { email, firstName } = req.body;

  console.log(`[VERIFY] Request received for: ${email}`);

  if (!email) {
    return res.status(400).json({ success: false, error: 'Email is required.' });
  }

  try {
    // [1] Generate Firebase verification link
    const rawLink = await adminAuth.generateEmailVerificationLink(
      email,
      {
        url            : `${process.env.FRONTEND_URL}/action.html`,
        handleCodeInApp: false
      }
    );

    // [2] Replace Firebase default handler with our custom page
    //     Before: https://[project].firebaseapp.com/__/auth/action?mode=verifyEmail&oobCode=...
    //     After:  https://mycybershieldai.web.app/action.html?mode=verifyEmail&oobCode=...
    const verificationLink = useCustomHandler(rawLink);

    console.log(`[VERIFY] Link points to: ${verificationLink.split('?')[0]}`);

    // [3] Send via SendGrid
    const result = await sendVerificationEmail({
      to              : email,
      firstName       : firstName || 'Analyst',
      verificationLink: verificationLink
    });

    if (!result.success) {
      console.error('[VERIFY] SendGrid failed:', result.error);
      return res.status(500).json({
        success: false,
        error  : 'Failed to send verification email. Please try again.'
      });
    }

    console.log(`[VERIFY] Email sent successfully to: ${email}`);
    res.status(200).json({ success: true, message: 'Verification email sent.' });

  } catch (error) {
    console.error('[VERIFY ERROR]', error.message);
    res.status(500).json({ success: false, error: error.message });
  }
});

// ─────────────────────────────────────────────
// POST /api/user/send-password-reset
// ─────────────────────────────────────────────

router.post('/send-password-reset', async (req, res) => {
  const { email } = req.body;

  console.log(`[RESET] Request received for: ${email}`);

  if (!email) {
    return res.status(400).json({ success: false, error: 'Email is required.' });
  }

  try {
    // [1] Look up user for their first name
    let firstName = 'Analyst';

    try {
      const userRecord = await adminAuth.getUserByEmail(email);
      const profileDoc = await db.collection('users').doc(userRecord.uid).get();
      if (profileDoc.exists && profileDoc.data().firstName) {
        firstName = profileDoc.data().firstName;
      }
    } catch (lookupError) {
      // Email not registered — silent success prevents user enumeration
      console.log(`[RESET] Email not found: ${email} — returning silent success`);
      return res.status(200).json({ success: true });
    }

    // [2] Generate Firebase password reset link
    const rawLink = await adminAuth.generatePasswordResetLink(
      email,
      {
        url            : `${process.env.FRONTEND_URL}/action.html`,
        handleCodeInApp: false
      }
    );

    // [3] Replace Firebase default handler with our custom page
    //     Before: https://[project].firebaseapp.com/__/auth/action?mode=resetPassword&oobCode=...
    //     After:  https://mycybershieldai.web.app/action.html?mode=resetPassword&oobCode=...
    const resetLink = useCustomHandler(rawLink);

    console.log(`[RESET] Link points to: ${resetLink.split('?')[0]}`);

    // [4] Send via SendGrid
    const result = await sendPasswordResetEmail({
      to       : email,
      firstName: firstName,
      resetLink: resetLink
    });

    if (!result.success) {
      console.error('[RESET] SendGrid failed:', result.error);
      return res.status(500).json({
        success: false,
        error  : 'Failed to send reset email. Please try again.'
      });
    }

    console.log(`[RESET] Email sent to: ${email}`);
    res.status(200).json({ success: true });

  } catch (error) {
    console.error('[RESET ERROR]', error.message);
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;